version: "3.9"
services:
    client:
        container_name: client
        restart: always
        build: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - "3000:3000"
        links:
            - server
    server:
        container_name: server
        restart: always
        build: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - "4000:4000"
        environment:
            - POSTGRES_URI=postgres://mauricemurphy:password@postgres:5432/app
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=mauricemurphy
            - POSTGRES_PASSWORD=password
            - POSTRES_DB=perntodo
            - POSTGRES_HOST=postgres
        volumes:
            - ./data:/data/db
        ports:
            - "5432:5432"
volumes:
    db-data:
