export const ActionTypes = {
    ADD_TODO_PENDING: "ADD_TODO_PENDING",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_ERROR: "ADD_TODO_ERROR",

    GET_TODOS_PENDING: "GET_TODOS_PENDING",
    GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
    GET_TODOS_ERROR: "GET_TODOS_ERROR",

    UPDATE_TODO_PENDING: "UPDATE_TODO_PENDING",
    UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
    UPDATE_TODO_ERROR: "UPDATE_TODO_ERROR",

    REMOVE_TODO_PENDING: "REMOVE_TODO_PENDING",
    REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
    REMOVE_TODO_ERROR: "REMOVE_TODO_ERROR",
};
